name: Docs
on:
  push:
    branches: [master]
permissions:
  contents: read
  pages: write
  id-token: write
concurrency:
  group: deploy
  cancel-in-progress: false
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Setup Rust
        uses: dtolnay/rust-toolchain@stable
      - name: Configure cache
        uses: Swatinem/rust-cache@v2
      - name: Setup pages
        id: pages
        uses: actions/configure-pages@v5
      - uses: extractions/setup-just@v3
        with:
          just-version: 1.5.0 # optional semver specification, otherwise latest
      - name: Install Zola
        run: |
          # Get latest tag (e.g., "v0.18.0")
          ZOLA_TAG=$(curl -s https://api.github.com/repos/getzola/zola/releases/latest | jq -r .tag_name)

          # Strip the 'v' prefix (e.g., "v0.18.0" -> "0.18.0")
          ZOLA_VERSION=${ZOLA_TAG#v}

          # Build the correct asset name
          ASSET="zola-v${ZOLA_VERSION}-x86_64-unknown-linux-gnu.tar.gz"

          # Download the actual release tarball
          curl -sL "https://github.com/getzola/zola/releases/download/${ZOLA_TAG}/${ASSET}" -o zola.tar.gz

          # Unpack and install
          tar -xzf zola.tar.gz
          sudo mv zola /usr/local/bin
      - name: Download TailwindCSS CLI
        run: |
          TAILWIND_VERSION="v3.4.16"
          ARCH=$(uname -m)
          case "$ARCH" in
            x86_64)
              echo "Detected architecture: x86_64"
              curl -sLO https://github.com/tailwindlabs/tailwindcss/releases/download/${TAILWIND_VERSION}/tailwindcss-linux-x64
              chmod +x tailwindcss-linux-x64
              sudo mv tailwindcss-linux-x64 /usr/local/bin/tailwindcss
              ;;
            aarch64)
              echo "Detected architecture: aarch64"
              curl -sLO https://github.com/tailwindlabs/tailwindcss/releases/download/${TAILWIND_VERSION}/tailwindcss-linux-arm64
              chmod +x tailwindcss-linux-arm64
              sudo mv tailwindcss-linux-arm64 /usr/local/bin/tailwindcss
              ;;
            *)
              echo "Unsupported architecture: $ARCH"
              exit 1
              ;;
          esac
      - name: Run build
        run: just build
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: build/www/public
  deploy:
    name: Deploy
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
